In [1]:
import pandas as pd

In [9]:
oly_file = pd.read_csv("C:/Users/aakan/Desktop/Stevens/Semester 2/Self_Study/Python/Pandas/Olympics/Python_Project/olympics.csv",skiprows=4)

In [10]:
oly_file

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
6,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200m freestyle,M,Gold
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
9,Athens,1896,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400m freestyle,M,Gold
10,Athens,1896,Aquatics,Swimming,"PEPANOS, Antonios",GRE,Men,400m freestyle,M,Silver
11,Athens,1896,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
12,Athens,1896,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
14,Athens,1896,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
16,Athens,1896,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110m hurdles,M,Silver
17,Athens,1896,Athletics,Athletics,"LERMUSIAUX, Albin",FRA,Men,1500m,M,Bronze
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
20,Athens,1896,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400m,M,Bronze
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
22,Athens,1896,Athletics,Athletics,"JAMISON, Herbert",USA,Men,400m,M,Silver
23,Athens,1896,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800m,M,Bronze
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
26,Athens,1896,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,discus throw,M,Bronze
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
28,Athens,1896,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,discus throw,M,Silver
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...,...
29186,Beijing,2008,Wrestling,Wrestling Free.,"MUTALIMOV, Marid",KAZ,Men,96 - 120kg,M,Bronze
29187,Beijing,2008,Wrestling,Wrestling Free.,"TAYMAZOV, Artur",UZB,Men,96 - 120kg,M,Gold
29188,Beijing,2008,Wrestling,Wrestling Free.,"AKHMEDOV, Bakhtiyar",RUS,Men,96 - 120kg,M,Silver
29189,Beijing,2008,Wrestling,Wrestling Gre-R,"AMOYAN, Roman",ARM,Men,- 55kg,M,Bronze
29190,Beijing,2008,Wrestling,Wrestling Gre-R,"PARK, Eun-Chul",KOR,Men,- 55kg,M,Bronze
29191,Beijing,2008,Wrestling,Wrestling Gre-R,"MANKIEV, Nazyr",RUS,Men,- 55kg,M,Gold
29192,Beijing,2008,Wrestling,Wrestling Gre-R,"BAYRAMOV, Rovshan",AZE,Men,- 55kg,M,Silver
29193,Beijing,2008,Wrestling,Wrestling Gre-R,"TENGIZBAYEV, Nurbakyt",KAZ,Men,55 - 60kg,M,Bronze
29194,Beijing,2008,Wrestling,Wrestling Gre-R,"TIUMENBAEV, Ruslan",KGZ,Men,55 - 60kg,M,Bronze
29195,Beijing,2008,Wrestling,Wrestling Gre-R,"ALBIEV, Islam-Beka",RUS,Men,55 - 60kg,M,Gold
29196,Beijing,2008,Wrestling,Wrestling Gre-R,"RAHIMOV, Vitaliy",AZE,Men,55 - 60kg,M,Silver
29197,Beijing,2008,Wrestling,Wrestling Gre-R,"SIAMIONAU, Mikhail",BLR,Men,60 - 66kg,M,Bronze
29198,Beijing,2008,Wrestling,Wrestling Gre-R,"VARDANYAN, Armen",UKR,Men,60 - 66kg,M,Bronze
29199,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Steeve",FRA,Men,60 - 66kg,M,Gold
29200,Beijing,2008,Wrestling,Wrestling Gre-R,"BEGALIEV, Kanatbek",KGZ,Men,60 - 66kg,M,Silver
29201,Beijing,2008,Wrestling,Wrestling Gre-R,"GUENOT, Christophe",FRA,Men,66 - 74kg,M,Bronze
29202,Beijing,2008,Wrestling,Wrestling Gre-R,"YANAKIEV, Yavor",BUL,Men,66 - 74kg,M,Bronze
29203,Beijing,2008,Wrestling,Wrestling Gre-R,"KVIRKELIA, Manuchar",GEO,Men,66 - 74kg,M,Gold
29204,Beijing,2008,Wrestling,Wrestling Gre-R,"CHANG, Yongxiang",CHN,Men,66 - 74kg,M,Silver
29205,Beijing,2008,Wrestling,Wrestling Gre-R,"AVLUCA, Nazmi",TUR,Men,74 - 84kg,M,Bronze
29206,Beijing,2008,Wrestling,Wrestling Gre-R,"MINGUZZI, Andrea",ITA,Men,74 - 84kg,M,Gold
29207,Beijing,2008,Wrestling,Wrestling Gre-R,"FODOR, Zoltan",HUN,Men,74 - 84kg,M,Silver
29208,Beijing,2008,Wrestling,Wrestling Gre-R,"MAMBETOV, Asset",KAZ,Men,84 - 96kg,M,Bronze
29209,Beijing,2008,Wrestling,Wrestling Gre-R,"WHEELER, Adam",USA,Men,84 - 96kg,M,Bronze
29210,Beijing,2008,Wrestling,Wrestling Gre-R,"KHUSHTOV, Aslanbek",RUS,Men,84 - 96kg,M,Gold
29211,Beijing,2008,Wrestling,Wrestling Gre-R,"ENGLICH, Mirko",GER,Men,84 - 96kg,M,Silver
29212,Beijing,2008,Wrestling,Wrestling Gre-R,"MIZGAITIS, Mindaugas",LTU,Men,96 - 120kg,M,Bronze
29213,Beijing,2008,Wrestling,Wrestling Gre-R,"PATRIKEEV, Yuri",ARM,Men,96 - 120kg,M,Bronze
29214,Beijing,2008,Wrestling,Wrestling Gre-R,"LOPEZ, Mijain",CUB,Men,96 - 120kg,M,Gold
29215,Beijing,2008,Wrestling,Wrestling Gre-R,"BAROEV, Khasan",RUS,Men,96 - 120kg,M,Silver

In [12]:
type(oly_file['NOC'])

pandas.core.series.Series

In [14]:
type(oly_file.NOC)

pandas.core.series.Series

In [16]:
oly_file[['Edition','City','Athlete','Medal']]

       Edition     City                      Athlete   Medal
0         1896   Athens                HAJOS, Alfred    Gold
1         1896   Athens             HERSCHMANN, Otto  Silver
2         1896   Athens            DRIVAS, Dimitrios  Bronze
3         1896   Athens           MALOKINIS, Ioannis    Gold
4         1896   Athens           CHASAPIS, Spiridon  Silver
5         1896   Athens        CHOROPHAS, Efstathios  Bronze
6         1896   Athens                HAJOS, Alfred    Gold
7         1896   Athens             ANDREOU, Joannis  Silver
8         1896   Athens        CHOROPHAS, Efstathios  Bronze
9         1896   Athens                NEUMANN, Paul    Gold
10        1896   Athens            PEPANOS, Antonios  Silver
11        1896   Athens                LANE, Francis  Bronze
12        1896   Athens             SZOKOLYI, Alajos  Bronze
13        1896   Athens                BURKE, Thomas    Gold
14        1896   Athens               HOFMANN, Fritz  Silver
15        1896   Athens               CURTIS, Thomas    Gold
16        1896   Athens           GOULDING, Grantley  Silver
17        1896   Athens            LERMUSIAUX, Albin  Bronze
18        1896   Athens                 FLACK, Edwin    Gold
19        1896   Athens                BLAKE, Arthur  Silver
20        1896   Athens              GMELIN, Charles  Bronze
21        1896   Athens                BURKE, Thomas    Gold
22        1896   Athens             JAMISON, Herbert  Silver
23        1896   Athens           GOLEMIS, Dimitrios  Bronze
24        1896   Athens                 FLACK, Edwin    Gold
25        1896   Athens                 DANI, Nandor  Silver
26        1896   Athens             VERSIS, Sotirios  Bronze
27        1896   Athens              GARRETT, Robert    Gold
28        1896   Athens  PARASKEVOPOULOS, Panagiotis  Silver
29        1896   Athens                CLARK, Ellery    Gold
...        ...      ...                          ...     ...
29186     2008  Beijing             MUTALIMOV, Marid  Bronze
29187     2008  Beijing              TAYMAZOV, Artur    Gold
29188     2008  Beijing          AKHMEDOV, Bakhtiyar  Silver
29189     2008  Beijing                AMOYAN, Roman  Bronze
29190     2008  Beijing               PARK, Eun-Chul  Bronze
29191     2008  Beijing               MANKIEV, Nazyr    Gold
29192     2008  Beijing            BAYRAMOV, Rovshan  Silver
29193     2008  Beijing        TENGIZBAYEV, Nurbakyt  Bronze
29194     2008  Beijing           TIUMENBAEV, Ruslan  Bronze
29195     2008  Beijing           ALBIEV, Islam-Beka    Gold
29196     2008  Beijing             RAHIMOV, Vitaliy  Silver
29197     2008  Beijing           SIAMIONAU, Mikhail  Bronze
29198     2008  Beijing             VARDANYAN, Armen  Bronze
29199     2008  Beijing               GUENOT, Steeve    Gold
29200     2008  Beijing           BEGALIEV, Kanatbek  Silver
29201     2008  Beijing           GUENOT, Christophe  Bronze
29202     2008  Beijing              YANAKIEV, Yavor  Bronze
29203     2008  Beijing          KVIRKELIA, Manuchar    Gold
29204     2008  Beijing             CHANG, Yongxiang  Silver
29205     2008  Beijing                AVLUCA, Nazmi  Bronze
29206     2008  Beijing             MINGUZZI, Andrea    Gold
29207     2008  Beijing                FODOR, Zoltan  Silver
29208     2008  Beijing              MAMBETOV, Asset  Bronze
29209     2008  Beijing                WHEELER, Adam  Bronze
29210     2008  Beijing           KHUSHTOV, Aslanbek    Gold
29211     2008  Beijing               ENGLICH, Mirko  Silver
29212     2008  Beijing         MIZGAITIS, Mindaugas  Bronze
29213     2008  Beijing              PATRIKEEV, Yuri  Bronze
29214     2008  Beijing                LOPEZ, Mijain    Gold
29215     2008  Beijing               BAROEV, Khasan  Silver

[29216 rows x 4 columns]

In [26]:
type(oly_file[['Edition','City','Athlete','Medal']])

pandas.core.frame.DataFrame

In [ ]:
# Events in which Jesse Owens won a medal

In [61]:
oly_file[oly_file.Athlete == 'OWENS, Jesse']['Event']

6427            100m
6439            200m
6456    4x100m relay
6523       long jump
Name: Event, dtype: object

In [28]:
# Country that has won most men`s gold medals in singles badminton

In [38]:
oly_file[(oly_file.Sport =='Badminton') & (oly_file.Gender == 'Men') & (oly_file.Event == 'singles') & (oly_file.Medal == 'Gold')].sort_values('Athlete')

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
20045,Barcelona,1992,Badminton,Badminton,"BUDI KUSUMA, Alan",INA,Men,singles,M,Gold
25734,Athens,2004,Badminton,Badminton,"HIDAYAT, Taufik",INA,Men,singles,M,Gold
21787,Atlanta,1996,Badminton,Badminton,"HOYER-LARSEN, Poul Erik",DEN,Men,singles,M,Gold
23717,Sydney,2000,Badminton,Badminton,"JI, Xinpeng",CHN,Men,singles,M,Gold
27741,Beijing,2008,Badminton,Badminton,"LIN, Dan",CHN,Men,singles,M,Gold

In [39]:
# Three countries that have won the most medals from1984 to 2008

In [40]:
oly_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
City            29216 non-null object
Edition         29216 non-null int64
Sport           29216 non-null object
Discipline      29216 non-null object
Athlete         29216 non-null object
NOC             29216 non-null object
Gender          29216 non-null object
Event           29216 non-null object
Event_gender    29216 non-null object
Medal           29216 non-null object
dtypes: int64(1), object(9)
memory usage: 2.2+ MB

In [69]:
oly_file[oly_file.Edition >= 1984].NOC.value_counts().head(3)

USA    1837
AUS     762
GER     691
Name: NOC, dtype: int64

In [47]:
# Men Gold Medal winners for 100m track and field sprint event

In [60]:
oly_file[((oly_file.Event == '100m') | (oly_file.Event == 'sprint')) & (oly_file.Gender == 'Men') & (oly_file.Medal == 'Gold')].sort_values('Edition',ascending=False)[['City','Edition','Athlete','NOC']]

                        City  Edition                Athlete  NOC
27552                Beijing     2008            BOLT, Usain  JAM
25539                 Athens     2004         GATLIN, Justin  USA
23521                 Sydney     2000        GREENE, Maurice  USA
21598                Atlanta     1996        BAILEY, Donovan  CAN
19859              Barcelona     1992      CHRISTIE, Linford  GBR
18284                  Seoul     1988            LEWIS, Carl  USA
16794            Los Angeles     1984            LEWIS, Carl  USA
15374                 Moscow     1980           WELLS, Allan  GBR
14069               Montreal     1976       CRAWFORD, Hasely  TRI
12902                 Munich     1972         BORZOV, Valery  URS
11865                 Mexico     1968       HINES, James Ray  USA
10823                  Tokyo     1964          HAYES, Robert  USA
9924                    Rome     1960            HARY, Armin  EUA
9009   Melbourne / Stockholm     1956  MORROW, Robert Joseph  USA
8121                Helsinki     1952        REMIGINO, Lindy  USA
7302                  London     1948      DILLARD, Harrison  USA
6427                  Berlin     1936           OWENS, Jesse  USA
5806             Los Angeles     1932           TOLAN, Eddie  USA
5095               Amsterdam     1928        WILLIAMS, Percy  CAN
4236                   Paris     1924       ABRAHAMS, Harold  GBR
2996                 Antwerp     1920       PADDOCK, Charles  USA
2022               Stockholm     1912           CRAIG, Ralph  USA
1191                  London     1908       WALKER, Reginald  RSA
737                 St Louis     1904           HAHN, Archie  USA
231                    Paris     1900        JARVIS, Francis  USA
13                    Athens     1896          BURKE, Thomas  USA